import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { ethers, providers } from "ethers";
import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  const [currentAccount, setCurrentAccount] = useState(null);

  const connectWallet = async () => {
    try {
      const { ethereum } = window;

      // check for injected provider
      if (!ethereum) {
        toast("You need Metamask to sign in", { icon: "🦊" });
        return;
      }

      // ensure user is on rinkeby
      let chainId = await ethereum.request({ method: 'eth_chainId' })
      console.log('chainId', chainId)

      if (chainId !== '0x4') {
        toast("Please switch to rinkeby")
        // switch user to mumbai
        await switchNetwork();
      }

    } catch (error) {
      console.log(error);
    }
  }

  const switchNetwork = async () => {
  	if (window.ethereum) {
  		try {
  			// Try to switch to rinkeby
  			await window.ethereum.request({
  				method: 'wallet_switchEthereumChain',
  				params: [{ chainId: '0x4' }], // Check networks.js for hexadecimal network ids
  			});

        const accounts = await ethereum.request({ method: "eth_requestAccounts"});
        setCurrentAccount(accounts[0]);
        console.log("Connected to", accounts[0]);

  		} catch (error) {
        console.error('user rejected switch to rinkeby', error);
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NFTicket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to NFTicket!
        </h1>

        <p className={styles.description}>
          Sign in using the button below. Make sure you're on the Polygon Mumbai chain.
        </p>

        { !currentAccount
          ? 
          <button 
            className="rounded bg-red-200 hover:bg-slate-100 h-10 px-2 self-center"
            onClick={() => connectWallet()}>
            Sign In
          </button>
          : 
          <h1>You're signed in</h1>
        }


      </main>

      <Toaster/>
    </div>
  )
}
